using System;
using System.ComponentModel;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
using WinForms = System.Windows.Forms;

namespace HeavenBase
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        string chosenPath;

        #region Constructor
        /// <summary>
        /// Initializes things.
        /// </summary>
        public MainWindow()
        {
            InitializeComponent();
        }
        #endregion

        #region LoadDataGrid
        /// <summary>
        /// Loads all DataGrid's info.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void LoadButton_Click(object sender, RoutedEventArgs e)
        {
            if (string.IsNullOrEmpty(PathTextBox.Text) || !FamiliarProperties.PathIsValid(PathTextBox.Text))
            {
                PathTextBox.Text = "Invalid Folder Path";
                return;
            }
            infoGrid.AutoGeneratedColumns += DataGrid_AutoGeneratedColumns;
            try
            {
                infoGrid.ItemsSource = FamiliarProperties.LoadCollectionData(chosenPath);
            }
            catch (IOException)
            {
                PathTextBox.Text = "File(s) Is(Are) Being Used by Another Process";
            }
        }
        #endregion

        #region FolderDialog
        /// <summary>
        /// Gets the root folder for the .wz archives (ideally).
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void PathTextBox_Click(object sender, RoutedEventArgs e)
        {
            WinForms.FolderBrowserDialog fbd = new WinForms.FolderBrowserDialog();
            WinForms.DialogResult result = fbd.ShowDialog();
            if (result == WinForms.DialogResult.OK)
            {
                chosenPath = fbd.SelectedPath;
                ((TextBox)sender).Text = chosenPath;
            }
        }
        #endregion

        #region RowHighlight
        /// <summary>
        /// Makes the row of the selected cell highlighted as well.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void EventSetter_OnHandlerSelected(object sender, RoutedEventArgs e)
        {
            DataGridRow dgr = FindParent<DataGridRow>(sender as DataGridCell);
            dgr.Background = new SolidColorBrush(Colors.Gold);
        }

        private void EventSetter_OnHandlerLostFocus(object sender, RoutedEventArgs e)
        {
            DataGridRow dgr = FindParent<DataGridRow>(sender as DataGridCell);
            dgr.Background = new SolidColorBrush(Colors.White);
        }

        public static T FindParent<T>(DependencyObject child) where T : DependencyObject
        {
            //get parent item
            DependencyObject parentObject = VisualTreeHelper.GetParent(child);

            //we've reached the end of the tree
            if (parentObject == null) return null;

            //check if the parent matches the type we're looking for
            T parent = parentObject as T;
            if (parent != null)
                return parent;
            else
                return FindParent<T>(parentObject);
        }
        #endregion

        #region ColumnInitialSorting
        /// <summary>
        /// Changes the datagrid's initial sorting
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var firstCol = infoGrid.Columns[0];
            firstCol.SortDirection = ListSortDirection.Ascending;
            infoGrid.Items.SortDescriptions.Add(new SortDescription(infoGrid.Columns[0].SortMemberPath, ListSortDirection.Ascending));
        }
        #endregion

        #region SearchFilter
        /// <summary>
        /// Make the datagrid show only the elements which share the textbox's text
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void SearchTextBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            string filterText = ((TextBox)sender).Text;
            ICollectionView cv = CollectionViewSource.GetDefaultView(infoGrid.ItemsSource);

            if (!string.IsNullOrEmpty(filterText))
            {
                cv.Filter = o => {
                    /* change to get data row value */
                    Familiar p = o as Familiar;
                    return p.FamiliarID.ToString().ToUpper().Contains(filterText.ToUpper()) ||
                    p.MobName.ToUpper().Contains(filterText.ToUpper()) ||
                    p.CardName.ToUpper().Contains(filterText.ToUpper()) ||
                    p.Rarity.ToUpper().Contains(filterText.ToUpper()) ||
                    p.SkillName.ToUpper().Contains(filterText.ToUpper()) ||
                    p.SkillDescription.ToUpper().Contains(filterText.ToUpper()) ||
                    p.Range.ToString().ToUpper().Contains(filterText.ToUpper()) ||
                    p.PassiveEffect.ToUpper().Contains(filterText.ToUpper()) ||
                    p.MobID.ToString().ToUpper().Contains(filterText.ToUpper()) ||
                    p.CardID.ToString().ToUpper().Contains(filterText.ToUpper()) ||
                    p.SkillID.ToString().ToUpper().Contains(filterText.ToUpper()) ||
                    p.PassiveEffectID.ToString().ToUpper().Contains(filterText.ToUpper()) ||
                    p.Level.ToString().ToUpper().Contains(filterText.ToUpper()) ||
                    p.Att.ToString().ToUpper().Contains(filterText.ToUpper()) ||
                    p.PassiveEffectBonus.ToString().ToUpper().Contains(filterText.ToUpper()) ||
                    p.SkillCategory.ToUpper().Contains(filterText.ToUpper());
                    /* end change to get data row value */
                };
            } else
            {
                cv.Filter = null;
            }
        }

        #endregion

        private void InfoGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if(e.PropertyName == "CardImage")
            {
                var templateColumn = new DataGridTemplateColumn();
                templateColumn.Header = e.PropertyName;
                e.Column = templateColumn;
            }
        }
    }
}
