using System;
using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
using WinForms = System.Windows.Forms;

namespace HeavenBase
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        string chosenPath;

        public MainWindow()
        {
            InitializeComponent();
        }

        private void LoadButton_Click(object sender, RoutedEventArgs e)
        {
            if (string.IsNullOrEmpty(PathTextBox.Text) || !FamiliarProperties.PathIsValid(PathTextBox.Text))
                return;
            infoGrid.AutoGeneratedColumns += DataGrid_AutoGeneratedColumns;
            infoGrid.ItemsSource = FamiliarProperties.LoadCollectionData(chosenPath);
        }

        private void PathTextBox_Click(object sender, RoutedEventArgs e)
        {
            WinForms.FolderBrowserDialog fbd = new WinForms.FolderBrowserDialog();
            WinForms.DialogResult result = fbd.ShowDialog();
            if (result == WinForms.DialogResult.OK)
            {
                chosenPath = fbd.SelectedPath;
                ((TextBox)sender).Text = chosenPath;
            }
        }

        private void EventSetter_OnHandlerSelected(object sender, RoutedEventArgs e)
        {
            DataGridRow dgr = FindParent<DataGridRow>(sender as DataGridCell);
            dgr.Background = new SolidColorBrush(Colors.Gold);
        }

        private void EventSetter_OnHandlerLostFocus(object sender, RoutedEventArgs e)
        {
            DataGridRow dgr = FindParent<DataGridRow>(sender as DataGridCell);
            dgr.Background = new SolidColorBrush(Colors.White);
        }

        public static T FindParent<T>(DependencyObject child) where T : DependencyObject
        {
            //get parent item
            DependencyObject parentObject = VisualTreeHelper.GetParent(child);

            //we've reached the end of the tree
            if (parentObject == null) return null;

            //check if the parent matches the type we're looking for
            T parent = parentObject as T;
            if (parent != null)
                return parent;
            else
                return FindParent<T>(parentObject);
        }

       void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var firstCol = infoGrid.Columns[0];
            firstCol.SortDirection = ListSortDirection.Ascending;
            infoGrid.Items.SortDescriptions.Add(new SortDescription(infoGrid.Columns[0].SortMemberPath, ListSortDirection.Ascending));
        }
    }
}
